tap "c-bata/kube-prompt"
tap "golangci/tap"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "rcmdnk/file"
brew "libpcap"
brew "arp-scan"
brew "autoconf"
brew "bash-completion"
brew "ghc"
brew "cabal-install"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gdbm"
brew "gettext"
brew "libffi"
brew "openssl@1.1"
brew "readline", link: true
brew "sqlite"
brew "glib"
brew "cairo"
brew "circleci"
brew "cmake"
brew "direnv"
brew "dive"
brew "libtiff"
brew "wxmac"
brew "erlang"
brew "fribidi"
brew "fzf"
brew "gmp"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "webp"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "git"
brew "gnu-getopt"
brew "jasper"
brew "graphicsmagick"
brew "netpbm"
brew "gts"
brew "icu4c"
brew "harfbuzz"
brew "pango"
brew "python@3.8"
brew "graphviz"
brew "ncurses"
brew "htop"
brew "hub"
brew "ilmbase"
brew "shared-mime-info"
brew "libheif"
brew "libomp"
brew "imagemagick"
brew "oniguruma"
brew "jq"
brew "k9s"
brew "krb5"
brew "kubernetes-cli"
brew "lazygit"
brew "libevent"
brew "libidn2"
brew "libyaml"
brew "lua"
brew "mas"
brew "md5sha1sum"
brew "mkcert"
brew "netdata", restart_service: true
brew "nkf"
brew "nmap"
brew "node"
brew "node-build"
brew "peco"
brew "perl"
brew "pict"
brew "postgresql"
brew "redis"
brew "ruby"
brew "sl"
brew "telnet"
brew "tidy-html5"
brew "utf8proc"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "c-bata/kube-prompt/kube-prompt"
brew "golangci/tap/golangci-lint"
brew "heroku/brew/heroku"
brew "rcmdnk/file/brew-file"
cask "adoptopenjdk8"
cask "appcleaner"
cask "clipy"
cask "docker"
cask "drawio"
cask "iterm2"
cask "karabiner-elements"
cask "postman"
cask "sequel-ace"
cask "visual-studio-code"
cask "wireshark"
cask "zoom"
cask "zoomus"
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "LINE", id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Simplenote", id: 692867256
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
