#!/bin/sh
cp ~/.config/karabiner/karabiner.json ./karabiner
mkdir -p ./karabiner/assets/complex_modifications
cp -pR ~/.config/karabiner/assets/complex_modifications/* ./karabiner/assets/complex_modifications
brew bundle dump
