#!/bin/bash
echo 'Create links'
DIRS=(asdf terminal vim zsh ruby tmux)
DOT_HOME=$HOME/dotfiles
for dir in ${DIRS[@]}
do
  echo "--- $dir ---"
  for f in $(ls -A $DOT_HOME/$dir)
  do
    echo $f
    ln -f "$DOT_HOME/$dir/$f" $HOME/$f
  done
done

if [ "$(uname -s)" = "Linux" ]; then
  echo "--- ghostty ---"
  GHOSTTY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty"
  mkdir -p "$GHOSTTY_CONFIG_DIR"
  for f in $(ls -A $DOT_HOME/ghostty)
  do
    echo $f
    ln -f "$DOT_HOME/ghostty/$f" "$GHOSTTY_CONFIG_DIR/$f"
  done
fi
