#!/bin/bash
echo 'Create links'
DIRS=(asdf terminal vim zsh ruby tmux)
DOT_HOME=$HOME/dotfiles
for dir in ${DIRS[@]}
do
  echo "--- $dir ---"
  for f in $(ls -A $DOT_HOME/$dir)
  do
    echo $f
    ln -f "$DOT_HOME/$dir/$f" $HOME/$f
  done
done

if [ "$(uname -s)" = "Linux" ]; then
  XDG_CONFIG_BASE="${XDG_CONFIG_HOME:-$HOME/.config}"
  XDG_CONFIG_DIRS=(ghostty herdr)
  for name in "${XDG_CONFIG_DIRS[@]}"
  do
    echo "--- $name ---"
    config_dir="$XDG_CONFIG_BASE/$name"
    mkdir -p "$config_dir"
    for f in $(ls -A "$DOT_HOME/$name")
    do
      echo $f
      ln -f "$DOT_HOME/$name/$f" "$config_dir/$f"
    done
  done
fi
